package Entities;
// Generated 2018-09-24 15:15:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ConsultationId generated by hbm2java
 */
public class ConsultationId  implements java.io.Serializable {


     private long codedocteur;
     private long numdos;
     private Date datec;

    public ConsultationId() {
    }

    public ConsultationId(long codedocteur, long numdos, Date datec) {
       this.codedocteur = codedocteur;
       this.numdos = numdos;
       this.datec = datec;
    }
   
    public long getCodedocteur() {
        return this.codedocteur;
    }
    
    public void setCodedocteur(long codedocteur) {
        this.codedocteur = codedocteur;
    }
    public long getNumdos() {
        return this.numdos;
    }
    
    public void setNumdos(long numdos) {
        this.numdos = numdos;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsultationId) ) return false;
		 ConsultationId castOther = ( ConsultationId ) other; 
         
		 return (this.getCodedocteur()==castOther.getCodedocteur())
 && (this.getNumdos()==castOther.getNumdos())
 && ( (this.getDatec()==castOther.getDatec()) || ( this.getDatec()!=null && castOther.getDatec()!=null && this.getDatec().equals(castOther.getDatec()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCodedocteur();
         result = 37 * result + (int) this.getNumdos();
         result = 37 * result + ( getDatec() == null ? 0 : this.getDatec().hashCode() );
         return result;
   }   


}


