package Entities;
// Generated 2018-09-24 15:15:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docteur generated by hbm2java
 */
public class Docteur  implements java.io.Serializable {


     private long matricule;
     private Specialite specialite;
     private String nomm;
     private String prenomm;
     private String ville;
     private String adresse;
     private String niveau;
     private Short nbrpatients;
     private Set dossierpatients = new HashSet(0);
     private Set consultations = new HashSet(0);

    public Docteur() {
    }

	
    public Docteur(long matricule, String nomm, String prenomm) {
        this.matricule = matricule;
        this.nomm = nomm;
        this.prenomm = prenomm;
    }
    public Docteur(long matricule, Specialite specialite, String nomm, String prenomm, String ville, String adresse, String niveau, Short nbrpatients, Set dossierpatients, Set consultations) {
       this.matricule = matricule;
       this.specialite = specialite;
       this.nomm = nomm;
       this.prenomm = prenomm;
       this.ville = ville;
       this.adresse = adresse;
       this.niveau = niveau;
       this.nbrpatients = nbrpatients;
       this.dossierpatients = dossierpatients;
       this.consultations = consultations;
    }
   
    public long getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(long matricule) {
        this.matricule = matricule;
    }
    public Specialite getSpecialite() {
        return this.specialite;
    }
    
    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }
    public String getNomm() {
        return this.nomm;
    }
    
    public void setNomm(String nomm) {
        this.nomm = nomm;
    }
    public String getPrenomm() {
        return this.prenomm;
    }
    
    public void setPrenomm(String prenomm) {
        this.prenomm = prenomm;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }
    public Short getNbrpatients() {
        return this.nbrpatients;
    }
    
    public void setNbrpatients(Short nbrpatients) {
        this.nbrpatients = nbrpatients;
    }
    public Set getDossierpatients() {
        return this.dossierpatients;
    }
    
    public void setDossierpatients(Set dossierpatients) {
        this.dossierpatients = dossierpatients;
    }
    public Set getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }




}


