package Entities;
// Generated 2018-09-24 15:15:24 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dossierpatient generated by hbm2java
 */
public class Dossierpatient  implements java.io.Serializable {


     private long numdos;
     private Docteur docteur;
     private String nomp;
     private String prenomp;
     private String genre;
     private String numas;
     private Date datenaiss;
     private Date datec;

    public Dossierpatient() {
    }

	
    public Dossierpatient(long numdos, String nomp, String prenomp) {
        this.numdos = numdos;
        this.nomp = nomp;
        this.prenomp = prenomp;
    }
    public Dossierpatient(long numdos, Docteur docteur, String nomp, String prenomp, String genre, String numas, Date datenaiss, Date datec) {
       this.numdos = numdos;
       this.docteur = docteur;
       this.nomp = nomp;
       this.prenomp = prenomp;
       this.genre = genre;
       this.numas = numas;
       this.datenaiss = datenaiss;
       this.datec = datec;
    }
   
    public long getNumdos() {
        return this.numdos;
    }
    
    public void setNumdos(long numdos) {
        this.numdos = numdos;
    }
    public Docteur getDocteur() {
        return this.docteur;
    }
    
    public void setDocteur(Docteur docteur) {
        this.docteur = docteur;
    }
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }
    public String getPrenomp() {
        return this.prenomp;
    }
    
    public void setPrenomp(String prenomp) {
        this.prenomp = prenomp;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getNumas() {
        return this.numas;
    }
    
    public void setNumas(String numas) {
        this.numas = numas;
    }
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }




}


