package Entities;
// Generated 2018-09-24 15:15:24 by Hibernate Tools 4.3.1



/**
 * OrdonnancemedicamentsId generated by hbm2java
 */
public class OrdonnancemedicamentsId  implements java.io.Serializable {


     private long numord;
     private long idmed;

    public OrdonnancemedicamentsId() {
    }

    public OrdonnancemedicamentsId(long numord, long idmed) {
       this.numord = numord;
       this.idmed = idmed;
    }
   
    public long getNumord() {
        return this.numord;
    }
    
    public void setNumord(long numord) {
        this.numord = numord;
    }
    public long getIdmed() {
        return this.idmed;
    }
    
    public void setIdmed(long idmed) {
        this.idmed = idmed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancemedicamentsId) ) return false;
		 OrdonnancemedicamentsId castOther = ( OrdonnancemedicamentsId ) other; 
         
		 return (this.getNumord()==castOther.getNumord())
 && (this.getIdmed()==castOther.getIdmed());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNumord();
         result = 37 * result + (int) this.getIdmed();
         return result;
   }   


}


