package Entities;
// Generated 2018-09-24 15:15:24 by Hibernate Tools 4.3.1



/**
 * OrdonnancechirurgieId generated by hbm2java
 */
public class OrdonnancechirurgieId  implements java.io.Serializable {


     private long numord;
     private byte rang;

    public OrdonnancechirurgieId() {
    }

    public OrdonnancechirurgieId(long numord, byte rang) {
       this.numord = numord;
       this.rang = rang;
    }
   
    public long getNumord() {
        return this.numord;
    }
    
    public void setNumord(long numord) {
        this.numord = numord;
    }
    public byte getRang() {
        return this.rang;
    }
    
    public void setRang(byte rang) {
        this.rang = rang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancechirurgieId) ) return false;
		 OrdonnancechirurgieId castOther = ( OrdonnancechirurgieId ) other; 
         
		 return (this.getNumord()==castOther.getNumord())
 && (this.getRang()==castOther.getRang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getNumord();
         result = 37 * result + this.getRang();
         return result;
   }   


}


